### ISSUE TITLE
Cannot seem to log in with my old accounts

### ISSUE THREAD

**Issue by JeremyZehr** [addrummond/newibexfarmissues#1]
I tried logging in on the new farm with two accounts that I've had for years on the original farm, and I get an "Invalid username or password" error message for both (I'm still able to log in on the original farm). Am I missing a step?

**Comment by addrummond** [comment]
Not missing a step - this is most likely a bug of some kind. Please give me the usernames (by email if you prefer not to reveal them here) and I'll be happy to look into it. Thanks for testing!

**Comment by JeremyZehr** [comment]
I tested my own account and a lab account shared by the different lab members. My username is JeremyZehr --- not giving the username of the shared account here, but happy to email it to you if you'd like to have both

**Comment by addrummond** [comment]
Fixed. See https://groups.google.com/g/ibexexperiments/c/-PTeVD39h9o/m/BStG8liNCQAJ
