### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by Alex-Cremers** [addrummond/newibexfarmissues#2]
When editing, the cursor appears half a line too high (see screenshot). Selection highlight is also half a line too high.

<img width="463" alt="Screenshot 2021-01-24 at 15 17 02" src="https://user-images.githubusercontent.com/6885146/105631503-74d1bc00-5e57-11eb-9430-0ddad33fe744.png">

The issue appears in all the browsers I tried (Firefox, Chrome and Safari). I'm running macOS Catalina (10.15.7).

**Comment by addrummond** [comment]
Thanks @Alex-Cremers . This should be fixed now.

It's just a CSS fix, so if you're still seeing the same issue now you probably just need to clear out your cache. (On Chrome, open the inspector then right click on the refresh button and select 'Empty cache and hard reload'.)

**Comment by Alex-Cremers** [comment]
Thanks for taking care so quickly! It's fixed indeed.
