### ISSUE TITLE
counter issue?

### ISSUE THREAD

**Issue by kentaron04** [addrummond/newibexfarmissues#4]
Hi, 

I don't know if this is a bug or a new design, but in the newer ibex farm, placing the __SetCounter__ function within shuffleSequence will increment the counter by 2: one with __SetCounter__ and another at the end of the experiment (?).  

See the following two identical experiments under the old and new ibex farms giving different results:
https://ibex.spellout.net/experiments/ultravisitor/shuffleorder/view
https://spellout.net/ibexexps/ultravisitor/shuffleorder/experiment.html

The code for data_includes is given below.
Thanks!

-Ken Nakatani

--------------------
var shuffleSequence = seq("setcounter", shuffle(anyOf("a", "b", "c", "d"), "filler"));
var defaults = [
    "DashedSentence", {
        mode: "self-paced reading"
    },
];

var items = [
    ["setcounter", "__SetCounter__", { }],

    [["a",1], "DashedSentence", {s: "1a"}],
    [["b",1], "DashedSentence", {s: "1b"}],
    [["c",1], "DashedSentence", {s: "1c"}],
    [["d",1], "DashedSentence", {s: "1d"}],

    [["a",2], "DashedSentence", {s: "2a"}],
    [["b",2], "DashedSentence", {s: "2b"}],
    [["c",2], "DashedSentence", {s: "2c"}],
    [["d",2], "DashedSentence", {s: "2d"}],

    [["a",3], "DashedSentence", {s: "3a"}],
    [["b",3], "DashedSentence", {s: "3b"}],
    [["c",3], "DashedSentence", {s: "3c"}],
    [["d",3], "DashedSentence", {s: "3d"}],

    [["a",4], "DashedSentence", {s: "4a"}],
    [["b",4], "DashedSentence", {s: "4b"}],
    [["c",4], "DashedSentence", {s: "4c"}],
    [["d",4], "DashedSentence", {s: "4d"}],

    ["filler", "DashedSentence", {s: "f1"}],
    ["filler", "DashedSentence", {s: "f2"}],
    ["filler", "DashedSentence", {s: "f3"}],
    ["filler", "DashedSentence", {s: "f4"}],
];

**Comment by addrummond** [comment]
Hi Ken,

This was indeed a bug. It should be fixed now.

Thank you again for a very detailed and helpful bug report.
