### ISSUE TITLE
zip archives empty

### ISSUE THREAD

**Issue by lisalevinson** [addrummond/newibexfarmissues#5]
Hello! I'm checking out my imported experiments on the new system for the first time. I wanted to download a zip archive to edit files and upload changes via the new procedure (I actually used to use the "esoteric" git repo option!), but all of the archives I've downloaded are empty zips. I'm not sure what parameters could be relevant to this, but this is one of the experiments: https://ibex.spellout.net/experiments/levinson/maze-demo/manage

I haven't made any changes to the files so far, they should be exactly as they imported (on this one I did generate 1 new result while testing, but the same happens with another with no new results). 

Love the new results format (though I have to re-write all of my scripts!). Thanks for your help.

**Comment by addrummond** [comment]
Hello Lisa,

> but all of the archives I've downloaded are empty zips

Hmm, I can't reproduce this issue if I log in to your account. If I download a zip for `made-demo`, all of the files are present. Perhaps this is a browser-specific issue? Which browser are you using? It might also be useful if you could email one of the empty zip files to me (a.d.drummond@gmail.com).

>Love the new results format (though I have to re-write all of my scripts!)

I'm glad you like the new format! Just in case this wasn't clear, you can also download results in the original format if you'd like to hold off on rewriting your scripts.

**Comment by lisalevinson** [comment]
Thanks - I tried to send you the file, but my email client actually forbid it, saying the file presents a "potential 5.7.0 security issue". After playing around a bit more it seems Windows thinks the zip files are "invalid" and won't extract them, though I can unzip using 7zip. See screenshot. 
![Screenshot 2021-02-10 160251](https://user-images.githubusercontent.com/15642952/107572389-390a5680-6bba-11eb-84be-f1a0e15bf6c2.jpg)

**Comment by addrummond** [comment]
Ah I see, no need to send the file then, it looks like the file is downloading correctly and it's just not compatible with some zip clients.

I will look into making it compatible with the built-in Windows unzip utility. Until then, the workaround is just to use a different utility to extract the files (such as 7zip).

**Comment by lisalevinson** [comment]
Great, thanks - I'm set for now in practical terms!

**Comment by addrummond** [comment]
Turned out to be a simple fix. The zips will open in the Windows file explorer now. 

The problem was that I was generating the zip table of contents with a leading `/` for all of the paths. It seems that most zip utilities tolerate this but that the built-in Windows unarchiver does not.

**Comment by lisalevinson** [comment]
Super, thanks!
